/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Yons Sánchez
 */
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form calculadora
     */
    //variables
    private String cadenaNumeros = "";
    private String operacion = "nula";
    private double primerNumero, resultado;
    private boolean activado = true;
    private boolean punto = true;
    
    public calculadora() {
        initComponents();
        this.setTitle("calculadora");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_c = new javax.swing.JButton();
        btn_raiz = new javax.swing.JButton();
        btn_divicion = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_multipcica = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_menos = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_suma = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_decimal = new javax.swing.JButton();
        btn_resultado_igual = new javax.swing.JButton();
        etiqueta_numeros = new javax.swing.JLabel();
        etiqueta_muestra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.GridLayout(5, 4));

        btn_c.setText("C");
        btn_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cActionPerformed(evt);
            }
        });
        jPanel2.add(btn_c);

        btn_raiz.setText(" √");
        btn_raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_raizActionPerformed(evt);
            }
        });
        jPanel2.add(btn_raiz);

        btn_divicion.setText("/");
        btn_divicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divicionActionPerformed(evt);
            }
        });
        jPanel2.add(btn_divicion);

        jButton5.setText("CE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        btn_7.setBackground(new java.awt.Color(0, 153, 153));
        btn_7.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btn_7.setText("7");
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_7);

        btn_8.setBackground(new java.awt.Color(0, 153, 153));
        btn_8.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_8);

        btn_9.setBackground(new java.awt.Color(0, 153, 153));
        btn_9.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_9);

        btn_multipcica.setText("X");
        btn_multipcica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multipcicaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_multipcica);

        btn_4.setBackground(new java.awt.Color(0, 153, 153));
        btn_4.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btn_4.setText("4");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_4);

        btn_5.setBackground(new java.awt.Color(0, 153, 153));
        btn_5.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_5);

        btn_6.setBackground(new java.awt.Color(0, 153, 153));
        btn_6.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_6);

        btn_menos.setText("-");
        btn_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menosActionPerformed(evt);
            }
        });
        jPanel2.add(btn_menos);

        btn_1.setBackground(new java.awt.Color(0, 153, 153));
        btn_1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btn_1.setText("1");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_1);

        btn_2.setBackground(new java.awt.Color(0, 153, 153));
        btn_2.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btn_2.setText("2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_2);

        btn_3.setBackground(new java.awt.Color(0, 153, 153));
        btn_3.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btn_3.setText("3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_3);

        btn_suma.setText("+");
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_suma);

        jButton18.setText("+/-");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton18);

        btn_0.setText("0");
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_0);

        btn_decimal.setText(".");
        btn_decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decimalActionPerformed(evt);
            }
        });
        jPanel2.add(btn_decimal);

        btn_resultado_igual.setText("=");
        btn_resultado_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resultado_igualActionPerformed(evt);
            }
        });
        jPanel2.add(btn_resultado_igual);

        etiqueta_numeros.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        etiqueta_numeros.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        etiqueta_numeros.setText("0");

        etiqueta_muestra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etiqueta_muestra.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(etiqueta_numeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
                    .addComponent(etiqueta_muestra, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiqueta_muestra, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiqueta_numeros, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_raizActionPerformed
        // TODO add your handling code here:
        primerNumero = Double.parseDouble(cadenaNumeros);
        etiqueta_muestra.setText("sqrt("+cadenaNumeros+")");
        resultado = Math.sqrt(primerNumero);
        etiqueta_numeros.setText(String.format("%.2f", resultado));
        //convertir de valor a cadena
        cadenaNumeros = String.valueOf(resultado); 
        
    }//GEN-LAST:event_btn_raizActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        // TODO add your handling code here:
        
         if(etiqueta_numeros.getText().equals("0")){
            cadenaNumeros = "6";
            
        }else{
            cadenaNumeros += "6";
        }
        
        etiqueta_numeros.setText(cadenaNumeros);
        activado = true;
         punto = true;
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        // TODO add your handling code here:
        if(etiqueta_numeros.getText().equals("0")){
            cadenaNumeros = "7";
            
        }else{
            cadenaNumeros += "7";
        }
        
        etiqueta_numeros.setText(cadenaNumeros);
        activado = true;
        
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        // TODO add your handling code here:
        
         if(etiqueta_numeros.getText().equals("0")){
            cadenaNumeros = "8";
            
        }else{
            cadenaNumeros += "8";
        }
        
        etiqueta_numeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        // TODO add your handling code here:
        
         if(etiqueta_numeros.getText().equals("0")){
            cadenaNumeros = "9";
            
        }else{
            cadenaNumeros += "9";
        }
        
        etiqueta_numeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // TODO add your handling code here:
        
         if(etiqueta_numeros.getText().equals("0")){
            cadenaNumeros = "4";
            
        }else{
            cadenaNumeros += "4";
        }
        
        etiqueta_numeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        // TODO add your handling code here:
         if(etiqueta_numeros.getText().equals("0")){
            cadenaNumeros = "5";
            
        }else{
            cadenaNumeros += "5";
        }
        
        etiqueta_numeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
         if(etiqueta_numeros.getText().equals("0")){
            cadenaNumeros = "1";
            
        }else{
            cadenaNumeros += "1";
        }
        
        etiqueta_numeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:
         if(etiqueta_numeros.getText().equals("0")){
            cadenaNumeros = "2";
            
        }else{
            cadenaNumeros += "2";
        }
        
        etiqueta_numeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:
        
         if(etiqueta_numeros.getText().equals("0")){
            cadenaNumeros = "3";
            
        }else{
            cadenaNumeros += "3";
        }
        
        etiqueta_numeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        // TODO add your handling code here:
        if(etiqueta_numeros.getText().equals("0")){
            cadenaNumeros = "0";
            
        }else{
            cadenaNumeros += "0";
        }
        
        etiqueta_numeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
        // TODO add your handling code here:
        
        if(activado == true){
            primerNumero = Double.parseDouble(cadenaNumeros);
            etiqueta_muestra.setText(cadenaNumeros + " + ");
            cadenaNumeros = "";
            operacion = "sumar";
            
            
            activado = false;
            punto = true;
            
        }
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_resultado_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resultado_igualActionPerformed
        // TODO add your handling code here:
        
        double segundonumero;
        //value of , devuelve canda convierte doble a string.
        if(operacion.equals("nula")){
            etiqueta_numeros.setText(cadenaNumeros);
        }
        
        //SUMA
       else if (operacion.equals("sumar")){
            segundonumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero + segundonumero;;
            etiqueta_numeros.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado); 
            operacion = "nula"; 
            //txt_.setText("");
            // txt_cadena.setText(""); 
        }
        
        //RESTA
          else if (operacion.equals("restar")){
            segundonumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero - segundonumero;;
            etiqueta_numeros.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado); 
            operacion = "nula"; 
            //txt_.setText("");
            // txt_cadena.setText(""); 
        }
        
        //DIVICION
          else if (operacion.equals("divicion")){
            segundonumero = Double.parseDouble(cadenaNumeros);
             if (segundonumero == 0) {
                 etiqueta_numeros.setText("no se divide");
                
            }else{
                 resultado = primerNumero / segundonumero;;
                 etiqueta_numeros.setText(String.format("% .2f", resultado));
                 cadenaNumeros = String.valueOf(resultado); 
                 operacion = "nula";
             }
        }
        
        //MULTIPLICACION
          else if (operacion.equals("multiplicacion")){
            segundonumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero * segundonumero;;
            etiqueta_numeros.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado); 
            operacion = "nula";
           // etiqueta_muestra.setText(operacion);
            //txt_.setText("");
            // txt_cadena.setText(""); 
        }
        
          etiqueta_muestra.setText("");
          activado = true;
           
    }//GEN-LAST:event_btn_resultado_igualActionPerformed

    private void btn_multipcicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multipcicaActionPerformed
        // TODO add your handling code here:
         if(activado == true){
            primerNumero = Double.parseDouble(cadenaNumeros);
            etiqueta_muestra.setText(cadenaNumeros + " x ");
            cadenaNumeros = "";
            operacion = "multiplicacion";
            
            
            activado = false;
            punto = true;
            
        }
      
    }//GEN-LAST:event_btn_multipcicaActionPerformed

    private void btn_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menosActionPerformed
        // TODO add your handling code here:
        
         if(activado == true){
            primerNumero = Double.parseDouble(cadenaNumeros);
            etiqueta_muestra.setText(cadenaNumeros + " - ");
            cadenaNumeros = "";
            operacion = "restar";
            
            
            activado = false;
             punto = true;
            
        }
    }//GEN-LAST:event_btn_menosActionPerformed

    private void btn_divicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divicionActionPerformed
        // TODO add your handling code here:
        
         if(activado == true){
            primerNumero = Double.parseDouble(cadenaNumeros);
            etiqueta_muestra.setText(cadenaNumeros + " / ");
            cadenaNumeros = "";
            operacion = "divicion";
            
            
            activado = false;
             punto = true;
            
        }
    }//GEN-LAST:event_btn_divicionActionPerformed

    private void btn_decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decimalActionPerformed
        // TODO add your handling code here:
        if(punto == true){
            if(cadenaNumeros.equals("")){
                cadenaNumeros = "0.";
                }else{
                cadenaNumeros += ".";
            }
            etiqueta_numeros.setText(cadenaNumeros);
            punto = false;
        }
    }//GEN-LAST:event_btn_decimalActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        if(cadenaNumeros.charAt(0) != '-'){
            cadenaNumeros = "-" + cadenaNumeros;
            
        }else{
            cadenaNumeros = cadenaNumeros.substring(1,cadenaNumeros.length());
        }
        etiqueta_numeros.setText(cadenaNumeros);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int tamano = cadenaNumeros.length();
        if (tamano > 0){
        if (tamano == 1){
            cadenaNumeros = "0";
            
        } else{
            cadenaNumeros = cadenaNumeros.substring(0,cadenaNumeros.length() -1);
            
        } 
        etiqueta_numeros.setText(cadenaNumeros);
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cActionPerformed
        // TODO add your handling code here:
        
        etiqueta_muestra.setText("");
        etiqueta_numeros.setText("0");
        operacion = "nula";
        cadenaNumeros = "";
        activado = true;
        punto = true;
    }//GEN-LAST:event_btn_cActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //constructor
    
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_c;
    private javax.swing.JButton btn_decimal;
    private javax.swing.JButton btn_divicion;
    private javax.swing.JButton btn_menos;
    private javax.swing.JButton btn_multipcica;
    private javax.swing.JButton btn_raiz;
    private javax.swing.JButton btn_resultado_igual;
    private javax.swing.JButton btn_suma;
    private javax.swing.JLabel etiqueta_muestra;
    private javax.swing.JLabel etiqueta_numeros;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
